import type { FamilyGroup, SearchHit } from './types'

const MARK = '【示意·非真库】'

function hit(
  partial: Omit<SearchHit, 'score'> & { score?: number },
): SearchHit {
  return { score: 0, ...partial }
}

/** ≥20 fake patents; ≥3 families with 2–4 members each. */
export const SEED_HITS: SearchHit[] = [
  // Family fam-battery-solid — CATL / 宁德 固态电解质 (3)
  hit({
    id: 'h01',
    publicationNumber: 'CN115123456A',
    title: '一种固态电解质及其制备方法',
    applicant: '宁德时代新能源科技股份有限公司',
    inventor: '张伟; 李明',
    date: '2023-06-15',
    ipc: ['H01M10/0562', 'H01M10/052'],
    familyId: 'fam-battery-solid',
    country: 'CN',
    legalStatus: '有效',
    abstract: `${MARK} 公开一种硫化物固态电解质，提升离子电导率与界面稳定性。`,
    snippet: '硫化物固态电解质 · 离子电导率',
    claims: '1. 一种固态电解质，其特征在于包含硫化物骨架与锂盐…',
  }),
  hit({
    id: 'h02',
    publicationNumber: 'US20230123456A1',
    title: 'Solid-state electrolyte and preparation thereof',
    applicant: 'Contemporary Amperex Technology Co., Limited',
    inventor: 'Zhang Wei; Li Ming',
    date: '2023-08-01',
    ipc: ['H01M10/0562'],
    familyId: 'fam-battery-solid',
    country: 'US',
    legalStatus: '审查中',
    abstract: `${MARK} A sulfide solid-state electrolyte with improved ionic conductivity.`,
    snippet: 'sulfide solid-state electrolyte',
    claims: '1. A solid-state electrolyte comprising a sulfide framework…',
  }),
  hit({
    id: 'h03',
    publicationNumber: 'EP4123456A1',
    title: 'Festelektrolyt und Herstellungsverfahren',
    applicant: 'Contemporary Amperex Technology Co., Limited',
    inventor: 'Zhang Wei',
    date: '2023-09-12',
    ipc: ['H01M10/0562', 'H01M10/058'],
    familyId: 'fam-battery-solid',
    country: 'EP',
    legalStatus: '审查中',
    abstract: `${MARK} Festkörperelektrolyt auf Sulfidbasis für Lithiumbatterien.`,
    snippet: 'Sulfid-Festelektrolyt',
    claims: '1. Ein Festelektrolyt, umfassend…',
  }),

  // Family fam-semicon-finfet — TSMC (3)
  hit({
    id: 'h04',
    publicationNumber: 'US11234567B2',
    title: 'FinFET structure with gate-all-around channel',
    applicant: 'Taiwan Semiconductor Manufacturing Company, Ltd.',
    inventor: 'Chen Yu; Wang Li',
    date: '2021-11-20',
    ipc: ['H01L29/66', 'H01L21/336'],
    familyId: 'fam-semicon-finfet',
    country: 'US',
    legalStatus: '有效',
    abstract: `${MARK} A FinFET device with wrapped gate and reduced short-channel effect.`,
    snippet: 'FinFET · gate-all-around',
    claims: '1. A semiconductor device comprising a fin structure…',
  }),
  hit({
    id: 'h05',
    publicationNumber: 'TW202145678A',
    title: '环绕栅极鳍式场效晶体管结构',
    applicant: '台湾积体电路制造股份有限公司',
    inventor: '陈宇; 王丽',
    date: '2021-12-01',
    ipc: ['H01L29/78'],
    familyId: 'fam-semicon-finfet',
    country: 'TW',
    legalStatus: '有效',
    abstract: `${MARK} 一种环绕栅极鳍式晶体管，改善短沟道效应。`,
    snippet: '环绕栅极 · FinFET',
    claims: '1. 一种半导体装置，包含鳍状结构…',
  }),
  hit({
    id: 'h06',
    publicationNumber: 'CN114567890A',
    title: '具有环绕栅极的鳍式场效应晶体管',
    applicant: '台湾积体电路制造股份有限公司',
    inventor: '陈宇',
    date: '2022-03-18',
    ipc: ['H01L29/66', 'H01L29/78'],
    familyId: 'fam-semicon-finfet',
    country: 'CN',
    legalStatus: '审查中',
    abstract: `${MARK} 公开环绕栅极通道结构及制造流程。`,
    snippet: '环绕栅极通道',
    claims: '1. 一种 FinFET 结构…',
  }),

  // Family fam-pharma-antibody — Roche (4)
  hit({
    id: 'h07',
    publicationNumber: 'WO2022156789A1',
    title: 'Bispecific antibody for oncology immunotherapy',
    applicant: 'F. Hoffmann-La Roche AG',
    inventor: 'Müller A.; Schmidt B.',
    date: '2022-07-28',
    ipc: ['A61K39/395', 'C07K16/28'],
    familyId: 'fam-pharma-antibody',
    country: 'WO',
    legalStatus: '审查中',
    abstract: `${MARK} Bispecific antibodies targeting PD-L1 and a tumor antigen.`,
    snippet: 'bispecific antibody · PD-L1',
    claims: '1. A bispecific antibody comprising…',
  }),
  hit({
    id: 'h08',
    publicationNumber: 'US20230198765A1',
    title: 'Methods of treating solid tumors with bispecific antibodies',
    applicant: 'Genentech, Inc.',
    inventor: 'Müller A.',
    date: '2023-02-14',
    ipc: ['A61K39/395', 'A61P35/00'],
    familyId: 'fam-pharma-antibody',
    country: 'US',
    legalStatus: '审查中',
    abstract: `${MARK} Treatment regimens using bispecific antibodies in solid tumors.`,
    snippet: 'solid tumors · immunotherapy',
    claims: '1. A method of treating a solid tumor…',
  }),
  hit({
    id: 'h09',
    publicationNumber: 'EP4234567A1',
    title: 'Bispezifischer Antikörper zur Tumortherapie',
    applicant: 'F. Hoffmann-La Roche AG',
    inventor: 'Schmidt B.',
    date: '2023-05-03',
    ipc: ['C07K16/28'],
    familyId: 'fam-pharma-antibody',
    country: 'EP',
    legalStatus: '审查中',
    abstract: `${MARK} Bispezifische Antikörper für die Onkologie.`,
    snippet: 'bispezifischer Antikörper',
    claims: '1. Ein bispezifischer Antikörper…',
  }),
  hit({
    id: 'h10',
    publicationNumber: 'CN116789012A',
    title: '用于肿瘤免疫治疗的双特异性抗体',
    applicant: '霍夫曼-拉罗奇有限公司',
    inventor: '米勒; 施密特',
    date: '2023-09-20',
    ipc: ['A61K39/395', 'C07K16/28'],
    familyId: 'fam-pharma-antibody',
    country: 'CN',
    legalStatus: '审查中',
    abstract: `${MARK} 靶向 PD-L1 与肿瘤抗原的双特异性抗体组合物。`,
    snippet: '双特异性抗体 · 肿瘤',
    claims: '1. 一种双特异性抗体…',
  }),

  // Family fam-comms-5g — Huawei / Qualcomm related (2) — wait need distinct families
  // Single + more singles to reach 20+

  hit({
    id: 'h11',
    publicationNumber: 'CN117890123A',
    title: '5G NR 波束管理方法及终端',
    applicant: '华为技术有限公司',
    inventor: '赵强; 刘洋',
    date: '2024-01-10',
    ipc: ['H04W16/28', 'H04W72/04'],
    familyId: 'fam-comms-beam',
    country: 'CN',
    legalStatus: '审查中',
    abstract: `${MARK} 一种用于毫米波频段的波束切换与测量报告方法。`,
    snippet: '5G NR · 波束管理',
    claims: '1. 一种波束管理方法…',
  }),
  hit({
    id: 'h12',
    publicationNumber: 'US20240111223A1',
    title: 'Beam management method and apparatus for NR',
    applicant: 'Huawei Technologies Co., Ltd.',
    inventor: 'Zhao Qiang; Liu Yang',
    date: '2024-04-04',
    ipc: ['H04W16/28', 'H04W72/04'],
    familyId: 'fam-comms-beam',
    country: 'US',
    legalStatus: '审查中',
    abstract: `${MARK} Beam switching and measurement reporting for mmWave NR.`,
    snippet: 'beam management · mmWave',
    claims: '1. A method of beam management…',
  }),
  hit({
    id: 'h13',
    publicationNumber: 'WO2024189012A1',
    title: 'Terminal apparatus for beam measurement reporting',
    applicant: 'Huawei Technologies Co., Ltd.',
    inventor: 'Liu Yang',
    date: '2024-06-18',
    ipc: ['H04W72/04'],
    familyId: 'fam-comms-beam',
    country: 'WO',
    legalStatus: '审查中',
    abstract: `${MARK} Terminal-side beam measurement reporting configuration.`,
    snippet: 'measurement reporting',
    claims: '1. A terminal apparatus…',
  }),

  // Singles
  hit({
    id: 'h14',
    publicationNumber: 'JP2023012345A',
    title: '全固体電池用負極活物質',
    applicant: 'トヨタ自動車株式会社',
    inventor: '田中一郎',
    date: '2023-01-25',
    ipc: ['H01M4/38', 'H01M10/0562'],
    familyId: 'fam-toyota-anode',
    country: 'JP',
    legalStatus: '有效',
    abstract: `${MARK} 全固体電池向けシリコン系負極活物質とその製造。`,
    snippet: '全固体電池 · 負極',
    claims: '1. 負極活物質であって…',
  }),
  hit({
    id: 'h15',
    publicationNumber: 'CN118234567A',
    title: '刀片电池模组热管理系统',
    applicant: '比亚迪股份有限公司',
    inventor: '王传福; 陈刚',
    date: '2024-08-22',
    ipc: ['H01M10/613', 'H01M10/625'],
    familyId: 'fam-byd-thermal',
    country: 'CN',
    legalStatus: '审查中',
    abstract: `${MARK} 刀片电池模组液冷板与热失控抑制结构。`,
    snippet: '刀片电池 · 热管理',
    claims: '1. 一种电池模组热管理系统…',
  }),
  hit({
    id: 'h16',
    publicationNumber: 'US10987654B1',
    title: 'Uplink control information multiplexing for 5G',
    applicant: 'QUALCOMM Incorporated',
    inventor: 'Patel R.; Kim S.',
    date: '2021-04-27',
    ipc: ['H04W72/04', 'H04L5/00'],
    familyId: 'fam-qc-uci',
    country: 'US',
    legalStatus: '有效',
    abstract: `${MARK} Multiplexing UCI on PUSCH for NR uplink.`,
    snippet: 'UCI multiplexing · PUSCH',
    claims: '1. A method of multiplexing uplink control information…',
  }),
  hit({
    id: 'h17',
    publicationNumber: 'KR102345678B1',
    title: '유기발광표시장치의 像素电路',
    applicant: '삼성디스플레이 주식회사',
    inventor: '김민수',
    date: '2020-09-15',
    ipc: ['H01L27/32', 'G09G3/3208'],
    familyId: 'fam-samsung-oled',
    country: 'KR',
    legalStatus: '有效',
    abstract: `${MARK} OLED 화소 보상 회로로 휘도 균일성을 개선한다.`,
    snippet: 'OLED · 화소회로',
    claims: '1. 유기발광표시장치의 화소회로…',
  }),
  hit({
    id: 'h18',
    publicationNumber: 'CN112345678B',
    title: '一种聚合物复合材料及其制备方法',
    applicant: '中国科学院化学研究所',
    inventor: '周杰; 吴芳',
    date: '2019-11-08',
    ipc: ['C08L23/06', 'C08K3/04'],
    familyId: 'fam-cas-polymer',
    country: 'CN',
    legalStatus: '有效',
    abstract: `${MARK} 石墨烯增强聚乙烯复合材料，提升导热与力学强度。`,
    snippet: '聚合物复合材料 · 石墨烯',
    claims: '1. 一种聚合物复合材料…',
  }),
  hit({
    id: 'h19',
    publicationNumber: 'US20220011234A1',
    title: 'Neural network accelerator with sparse attention',
    applicant: 'Samsung Electronics Co., Ltd.',
    inventor: 'Park J.; Lee H.',
    date: '2022-01-13',
    ipc: ['G06N3/063', 'G06N3/08'],
    familyId: 'fam-samsung-nn',
    country: 'US',
    legalStatus: '失效',
    abstract: `${MARK} Hardware accelerator for sparse transformer attention.`,
    snippet: 'neural network · sparse attention',
    claims: '1. A neural network accelerator comprising…',
  }),
  hit({
    id: 'h20',
    publicationNumber: 'CN109876543A',
    title: '锂离子电池隔膜涂覆浆料',
    applicant: '宁德时代新能源科技股份有限公司',
    inventor: '孙丽',
    date: '2018-06-05',
    ipc: ['H01M50/403', 'H01M50/449'],
    familyId: 'fam-catl-separator',
    country: 'CN',
    legalStatus: '失效',
    abstract: `${MARK} 陶瓷涂覆隔膜浆料配方，改善热收缩。`,
    snippet: '隔膜涂覆 · 陶瓷',
    claims: '1. 一种隔膜涂覆浆料…',
  }),
  hit({
    id: 'h21',
    publicationNumber: 'EP3987654B1',
    title: 'Polymer blend for automotive exterior parts',
    applicant: 'Toyota Motor Corporation',
    inventor: 'Suzuki K.',
    date: '2022-10-11',
    ipc: ['C08L67/02', 'C08L69/00'],
    familyId: 'fam-toyota-polymer',
    country: 'EP',
    legalStatus: '有效',
    abstract: `${MARK} Weather-resistant polymer blend for exterior trim.`,
    snippet: 'polymer blend · automotive',
    claims: '1. A polymer blend comprising…',
  }),
  hit({
    id: 'h22',
    publicationNumber: 'CN119001122A',
    title: '基于大模型的专利摘要生成方法',
    applicant: '华为技术有限公司',
    inventor: '陈思',
    date: '2025-02-28',
    ipc: ['G06N3/08', 'G06F40/216'],
    familyId: 'fam-huawei-llm',
    country: 'CN',
    legalStatus: '审查中',
    abstract: `${MARK} 利用预训练语言模型生成专利摘要的示意方法。`,
    snippet: '大模型 · 摘要生成',
    claims: '1. 一种摘要生成方法…',
  }),
  hit({
    id: 'h23',
    publicationNumber: 'US20250155678A1',
    title: 'Wireless sensing with MIMO radar waveforms',
    applicant: 'QUALCOMM Incorporated',
    inventor: 'Nguyen T.',
    date: '2025-06-12',
    ipc: ['H04W4/38', 'G01S13/02'],
    familyId: 'fam-qc-sensing',
    country: 'US',
    legalStatus: '审查中',
    abstract: `${MARK} Joint communication and sensing waveforms for MIMO radar.`,
    snippet: 'MIMO radar · wireless sensing',
    claims: '1. A method of wireless sensing…',
  }),
]

export function buildFamilies(hits: SearchHit[]): FamilyGroup[] {
  const map = new Map<string, SearchHit[]>()
  for (const h of hits) {
    const fid = h.familyId ?? h.id
    const list = map.get(fid) ?? []
    list.push(h)
    map.set(fid, list)
  }
  return [...map.entries()].map(([familyId, members]) => ({
    familyId,
    members: [...members].sort((a, b) => (b.score ?? 0) - (a.score ?? 0)),
  }))
}

export function createInitialHits(): SearchHit[] {
  return SEED_HITS.map((h) => ({ ...h, score: 0 }))
}
